# Generated by Django 6.0.6 on 2026-07-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='certificate_url',
        ),
    ]
